### ISSUE TITLE
Container starting but no internet within container

### ISSUE THREAD

**Issue by tardis89** [Kabe0/deluge-windscribe#37]
I am having an issue where the container starts both deluge and Windscribe, makes a connection to Windscribe servers, but once it's connected, there isn't actually any internet activity.

My docker-compose.yml is below:
```
version: '2.4'
services:
    deluge-windscribe:
        container_name: deluge-windscribe
        restart: unless-stopped
        image: deluge-windscribe
        expose:
            - "8112"
        ports:
            - 8112:8112 #deluge
            - 8989:8989 #sonarr
            - 7878:7878 #radarr
            - 9117:9117 #jackett
            - 58846:58846
        dns:
            - 8.8.8.8
        environment:
            - VPN_USERNAME=XXXXXXXXX
            - VPN_PASSWORD=XXXXXXXXXXXXXXX
            - VPN_LOCATION=US-W
            - WINDSCRIBE_FIREWALL=auto
            - LEGACY_IPTABLES=false
        volumes:
            - ${HOME}/.deluge-windscribe/config:/config
            - ${HOME}Downloads:/downloads            
        devices:
            - /dev/net/tun
        cap_add:
            - NET_ADMIN
    sonarr:
       depends_on: [deluge-windscribe]
       restart: unless-stopped
       network_mode: "service:deluge-windscribe"
       image: linuxserver/sonarr:latest
       environment:
         - PUID=1000
         - PGID=1000
       volumes:
         - ${HOME}/.deluge-windscribe/config/sonarr:/config
         - ${HOME}/downloads:/downloads
    jackett:
       depends_on: [deluge-windscribe]
       restart: unless-stopped
       network_mode: "service:deluge-windscribe"
       image: lscr.io/linuxserver/jackett:latest
       container_name: jackett
       environment:
         - PUID=1000
         - PGID=1000
         - TZ=America/Chicago
         - AUTO_UPDATE=true #optional
         - RUN_OPTS=-t -l #optional
       volumes:
         - ${HOME}/.deluge-windscribe/config/jackett/config:/config
         - ${HOME}/.deluge-windscribe/config/:/downloads
```

Output of windscribe.log:

> 2023-02-24 04:02:41,355 [INFO] Loading Account
> 2023-02-24 04:03:42,091 [INFO] Daemon: connected, running GET Session
> 2023-02-24 04:03:42,092 [INFO] GET Session
> 2023-02-24 04:03:42,097 [INFO] Starting new HTTPS connection (1): api.windscribe.com
> 2023-02-24 04:03:42,455 [DEBUG] "GET /Session?client_auth_hash=8175e732b9ba8cf5175e89974ae144c9&session_auth_hash=20876035%3A3%3A1677184767%3Ac0ea0866098012ec2604ebabc543571f3d9a7f839d%3A5ff990699d3ad3e92eea88e10abb4b0d2c8265f0ff&time=1677211422 HTTP/1.1" 200 None
> 2023-02-24 04:03:42,456 [INFO] Loading Account
> 2023-02-24 04:04:43,068 [INFO] Daemon: connected, running GET Session
> 2023-02-24 04:04:43,068 [INFO] GET Session
> 2023-02-24 04:04:43,072 [INFO] Starting new HTTPS connection (1): api.windscribe.com
> 2023-02-24 04:04:43,385 [DEBUG] "GET /Session?client_auth_hash=a3bebd5ca24370fc8851577492612587&session_auth_hash=20876035%3A3%3A1677184767%3Ac0ea0866098012ec2604ebabc543571f3d9a7f839d%3A5ff990699d3ad3e92eea88e10abb4b0d2c8265f0ff&time=1677211483 HTTP/1.1" 200 None
> 2023-02-24 04:04:43,386 [INFO] Loading Account

Output of opvn_log.txt:
> Thu Feb 23 20:39:29 2023 VERIFY EKU OK
> Thu Feb 23 20:39:29 2023 VERIFY OK: depth=0, C=CA, ST=ON, L=Toronto, O=Windscribe Limited, OU=Systems, CN=lax-107.windscribe.com
> Thu Feb 23 20:39:29 2023 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_AES_256_GCM_SHA384, 4096 bit RSA
> Thu Feb 23 20:39:29 2023 [lax-107.windscribe.com] Peer Connection Initiated with [AF_INET]89.41.26.51:443
> Thu Feb 23 20:39:30 2023 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
> Thu Feb 23 20:39:30 2023 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
> Thu Feb 23 20:39:30 2023 TUN/TAP device tun0 opened
> Thu Feb 23 20:39:30 2023 /sbin/ip link set dev tun0 up mtu 1500
> Thu Feb 23 20:39:30 2023 /sbin/ip addr add dev tun0 10.121.198.71/23 broadcast 10.121.199.255
> Thu Feb 23 20:39:30 2023 /etc/windscribe/update-resolv.sh tun0 1500 1552 10.121.198.71 255.255.254.0 init
> dhcp-option DOMAIN-ROUTE .
> dhcp-option DNS 10.255.255.2
> Thu Feb 23 20:39:30 2023 Initialization Sequence Completed
> Thu Feb 23 21:07:13 2023 AEAD Decrypt error: cipher final failed
> root@9a35c1acbcd5:/# til -f  /var/log/windscribe/ovpn_log.txt 
> bash: til: command not found
> root@9a35c1acbcd5:/# tail -f  /var/log/windscribe/ovpn_log.txt 
> Thu Feb 23 20:39:30 2023 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
> Thu Feb 23 20:39:30 2023 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
> Thu Feb 23 20:39:30 2023 TUN/TAP device tun0 opened
> Thu Feb 23 20:39:30 2023 /sbin/ip link set dev tun0 up mtu 1500
> Thu Feb 23 20:39:30 2023 /sbin/ip addr add dev tun0 10.121.198.71/23 broadcast 10.121.199.255
> Thu Feb 23 20:39:30 2023 /etc/windscribe/update-resolv.sh tun0 1500 1552 10.121.198.71 255.255.254.0 init
> dhcp-option DOMAIN-ROUTE .
> dhcp-option DNS 10.255.255.2
> Thu Feb 23 20:39:30 2023 Initialization Sequence Completed
> Thu Feb 23 21:07:13 2023 AEAD Decrypt error: cipher final failed
