### ISSUE TITLE
Config for Synology - and where to place config.ovpn?

### ISSUE THREAD

**Issue by Ltek** [Kabe0/deluge-windscribe#8]
I'm working to set this up on a Synology NAS. I have it running but not sure its 100% config'd properly.

A few questions.

1... where do I place the config.ovpn file?

2... when I use the Windscribe Config generator, it only allows me to select 1 location, not a region AND require to select a specific port from a list (cannot input the ports I have set in Docker). 
-- Will I need to open a port in Docker to allow for Windscribe?
-- How do we create a file for use that allows it to select the 'best' as ypu stated was the default in the container setup?

3... Do I need the below commands or do they run automatically when I start the container? I use Synology's Docker manager UI - not scripts or compose
- if they need to be added separately, how do I put them in? As Environment variables or something else?

 --cap-add=NET_ADMIN \
 --device /dev/net/tun:/dev/net/tun \

thanks for helping out a noobie!

**Comment by Ltek** [comment]
Is this Image no longer maintained?

**Comment by Kabe0** [comment]
Sorry, Have been crazy busy. 

So you don't use a config.ovpn file with this setup. This uses windscribe-cli to handle the network interfacing. So you only to make a config file with the username/pass of your windscribe login, or define it as environment variables to the docker container as described in the example.

You do need to have the --device assigned, otherwise the docker container will not have access to the proper network driver to make the correct tunnel settings. --cap-add=NET_ADMIN gives the docker container access to modify the /net/tun as by default docker are not authorised to make network modifications.

I have used Synology NAS's in the past. What are you using to configure the docker container? I should be albe to respond faster now.

**Comment by Ltek** [comment]
@Kabe0 
thx for the info. I'm really new to this. I installed Portainer - def over my head for now.

Can you help me build the proper Compose file?

I've see people use some settings, not sure if I need to?

**Comment by Kabe0** [comment]
This is my actual docker-compose file I have had running for the past 6 months
```
version: "3"
services:
  deluge-windscribe:
    restart: unless-stopped
    image: kabe0/deluge-windscribe:latest
    volumes:
      - ./downloads:/downloads
      - ./DelugeConfig:/config
    ports:
      - 8112:8112
      - 8989:8989
      - 58846:58846
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
```

A ./ represents the current directory. Inside the current directory, under DelugeConfig I have a config file called ```auth.conf``` with the three lines I mentioned above. The folde permissions for DelugeConfig are set to my user. You can find your user ID by typing
```id``` in your main system which will print out the uid and gid values. Make sure they match your variables on the container.
